### ISSUE TITLE
Projekt fails to build due to google test

### ISSUE THREAD

**Issue by abrock** [inkscape/lib2geom#7]
Hi,

I've been playing around with lib2geom a bit and I encountered a problem, so I thought I'd pull the latest git version.
Now my project doesn't build anymore, neither does a fresh clone of lib2geom.
I also upgraded google test to the latest git version, but that didn't help.

Here is how I tried to build lib2geom:

alexander@toothless:~/libs$ git clone https://github.com/inkscape/lib2geom.git
Cloning into 'lib2geom'...
remote: Counting objects: 18442, done.
remote: Total 18442 (delta 0), reused 0 (delta 0), pack-reused 18442
Receiving objects: 100% (18442/18442), 11.35 MiB | 2.32 MiB/s, done.
Resolving deltas: 100% (13927/13927), done.
Checking connectivity... done.
alexander@toothless:~/libs$ mkdir build-lib2geom
alexander@toothless:~/libs$ cd build-lib2geom/
alexander@toothless:~/libs/build-lib2geom$ cmake ../lib2geom/
-- The CXX compiler identification is GNU 6.1.1
-- The C compiler identification is GNU 6.1.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Boost version: 1.61.0
CMake Warning (dev) at CMakeScripts/Config2GeomDepends.cmake:20 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "gtk+-2.0_FOUND" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  CMakeLists.txt:12 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- gtk+-2.0 Includes, Compile and Link Flags: FOUND
-- gtkmm-2.4 Includes, Compile and Link Flags: FOUND
-- cairomm-1.0 Includes, Compile and Link Flags: FOUND
-- cairo Includes, Compile and Link Flags: FOUND
-- gsl Includes, Compile and Link Flags: FOUND
-- pycairo Includes, Compile and Link Flags: NOT FOUND
-- Performing Test HAVE_SINCOS
-- Performing Test HAVE_SINCOS - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alexander/libs/build-lib2geom
alexander@toothless:~/libs/build-lib2geom$ make -j8
Scanning dependencies of target gtest_main
Scanning dependencies of target gtest
Scanning dependencies of target 2geom
[  0%] Building CXX object src/gtest/CMakeFiles/gtest_main.dir/gtest_main.cc.o
[  0%] Building CXX object src/gtest/CMakeFiles/gtest.dir/gtest-all.cc.o
[  0%] Building CXX object src/2geom/CMakeFiles/2geom.dir/bezier.cpp.o
[  0%] Building CXX object src/2geom/CMakeFiles/2geom.dir/bezier-clipping.cpp.o
[  0%] Building CXX object src/2geom/CMakeFiles/2geom.dir/affine.cpp.o
[  1%] Building CXX object src/2geom/CMakeFiles/2geom.dir/bezier-curve.cpp.o
[  1%] Building CXX object src/2geom/CMakeFiles/2geom.dir/bezier-utils.cpp.o
[  2%] Building CXX object src/2geom/CMakeFiles/2geom.dir/basic-intersection.cpp.o
[  2%] Linking CXX static library libgtest_main.a
[  2%] Built target gtest_main
[  2%] Building CXX object src/2geom/CMakeFiles/2geom.dir/cairo-path-sink.cpp.o
[  3%] Building CXX object src/2geom/CMakeFiles/2geom.dir/circle.cpp.o
[  3%] Building CXX object src/2geom/CMakeFiles/2geom.dir/concepts.cpp.o
[  3%] Building CXX object src/2geom/CMakeFiles/2geom.dir/conicsec.cpp.o
[  4%] Building CXX object src/2geom/CMakeFiles/2geom.dir/conic_section_clipper_impl.cpp.o
[  4%] Building CXX object src/2geom/CMakeFiles/2geom.dir/convex-hull.cpp.o
[  4%] Building CXX object src/2geom/CMakeFiles/2geom.dir/coord.cpp.o
[  5%] Building CXX object src/2geom/CMakeFiles/2geom.dir/crossing.cpp.o
/home/alexander/libs/lib2geom/src/2geom/coord.cpp:3001:6: warning: ‘bool Geom::{anonymous}::DoubleToStringConverter::ToPrecision(double, int, std::__cxx11::string&) const’ defined but not used [-Wunused-function]
 bool DoubleToStringConverter::ToPrecision(double value,
      ^~~~~~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/2geom/coord.cpp:2953:6: warning: ‘bool Geom::{anonymous}::DoubleToStringConverter::ToExponential(double, int, std::__cxx11::string&) const’ defined but not used [-Wunused-function]
 bool DoubleToStringConverter::ToExponential(
      ^~~~~~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/2geom/coord.cpp:2916:6: warning: ‘bool Geom::{anonymous}::DoubleToStringConverter::ToFixed(double, int, std::__cxx11::string&) const’ defined but not used [-Wunused-function]
 bool DoubleToStringConverter::ToFixed(double value,
      ^~~~~~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/2geom/coord.cpp:1018:6: warning: ‘bool Geom::{anonymous}::Bignum::ToHexString(char*, int) const’ defined but not used [-Wunused-function]
 bool Bignum::ToHexString(char* buffer, int buffer_size) const {
      ^~~~~~
/home/alexander/libs/lib2geom/src/2geom/coord.cpp:634:6: warning: ‘void Geom::{anonymous}::Bignum::AssignHexString(Geom::{anonymous}::Vector<const char>)’ defined but not used [-Wunused-function]
 void Bignum::AssignHexString(Vector<const char> value) {
      ^~~~~~
[  5%] Building CXX object src/2geom/CMakeFiles/2geom.dir/curve.cpp.o
[  5%] Building CXX object src/2geom/CMakeFiles/2geom.dir/d2-sbasis.cpp.o
[  6%] Building CXX object src/2geom/CMakeFiles/2geom.dir/ellipse.cpp.o
[  6%] Building CXX object src/2geom/CMakeFiles/2geom.dir/elliptical-arc.cpp.o
/home/alexander/libs/lib2geom/src/2geom/curve.cpp: In member function ‘virtual std::vector<Geom::Intersection<> > Geom::Curve::intersectSelf(Geom::Coord) const’:
/home/alexander/libs/lib2geom/src/2geom/curve.cpp:111:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<Curve> deriv(derivative());
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/sbasis-to-bezier.h:39,
                 from /home/alexander/libs/lib2geom/src/2geom/curve.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  6%] Building CXX object src/2geom/CMakeFiles/2geom.dir/elliptical-arc-from-sbasis.cpp.o
/home/alexander/libs/lib2geom/src/2geom/elliptical-arc.cpp: In member function ‘virtual std::vector<Geom::Point> Geom::EllipticalArc::pointAndDerivatives(Geom::Coord, unsigned int) const’:
/home/alexander/libs/lib2geom/src/2geom/elliptical-arc.cpp:265:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> ea( static_cast<EllipticalArc*>(duplicate()) );
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /home/alexander/libs/lib2geom/src/2geom/elliptical-arc.cpp:35:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  7%] Building CXX object src/2geom/CMakeFiles/2geom.dir/geom.cpp.o
[  7%] Building CXX object src/2geom/CMakeFiles/2geom.dir/intersection-graph.cpp.o
[  7%] Building CXX object src/2geom/CMakeFiles/2geom.dir/line.cpp.o
[  8%] Linking CXX shared library libgtest.so
[  8%] Built target gtest
[  8%] Building CXX object src/2geom/CMakeFiles/2geom.dir/nearest-time.cpp.o
[  9%] Building CXX object src/2geom/CMakeFiles/2geom.dir/numeric/matrix.cpp.o
/home/alexander/libs/lib2geom/src/2geom/elliptical-arc-from-sbasis.cpp: In member function ‘bool Geom::make_elliptical_arc::make_elliptiarc()’:
/home/alexander/libs/lib2geom/src/2geom/elliptical-arc-from-sbasis.cpp:310:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc( e.arc(initial_point, inner_point, final_point) );
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/elliptical-arc.h:45,
                 from /home/alexander/libs/lib2geom/src/2geom/elliptical-arc-from-sbasis.cpp:36:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[  9%] Building CXX object src/2geom/CMakeFiles/2geom.dir/path-intersection.cpp.o
[  9%] Building CXX object src/2geom/CMakeFiles/2geom.dir/path-sink.cpp.o
[ 10%] Building CXX object src/2geom/CMakeFiles/2geom.dir/path.cpp.o
[ 10%] Building CXX object src/2geom/CMakeFiles/2geom.dir/pathvector.cpp.o
[ 10%] Building CXX object src/2geom/CMakeFiles/2geom.dir/piecewise.cpp.o
[ 11%] Building CXX object src/2geom/CMakeFiles/2geom.dir/point.cpp.o
[ 11%] Building CXX object src/2geom/CMakeFiles/2geom.dir/polynomial.cpp.o
[ 11%] Building CXX object src/2geom/CMakeFiles/2geom.dir/rect.cpp.o
[ 12%] Building CXX object src/2geom/CMakeFiles/2geom.dir/recursive-bezier-intersection.cpp.o
[ 12%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-2d.cpp.o
[ 12%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-geometric.cpp.o
[ 13%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-math.cpp.o
[ 13%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-poly.cpp.o
[ 13%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-roots.cpp.o
[ 14%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis-to-bezier.cpp.o
[ 14%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sbasis.cpp.o
[ 14%] Building CXX object src/2geom/CMakeFiles/2geom.dir/solve-bezier.cpp.o
[ 15%] Building CXX object src/2geom/CMakeFiles/2geom.dir/solve-bezier-one-d.cpp.o
[ 15%] Building CXX object src/2geom/CMakeFiles/2geom.dir/solve-bezier-parametric.cpp.o
[ 15%] Building CXX object src/2geom/CMakeFiles/2geom.dir/svg-path-parser.cpp.o
[ 15%] Building CXX object src/2geom/CMakeFiles/2geom.dir/svg-path-writer.cpp.o
[ 16%] Building CXX object src/2geom/CMakeFiles/2geom.dir/sweep-bounds.cpp.o
[ 16%] Building CXX object src/2geom/CMakeFiles/2geom.dir/utils.cpp.o
[ 16%] Building CXX object src/2geom/CMakeFiles/2geom.dir/transforms.cpp.o
[ 17%] Linking CXX static library lib2geom.a
[ 17%] Built target 2geom
Scanning dependencies of target circle-test
Scanning dependencies of target convex-hull-test
Scanning dependencies of target elliptical-arc-test
Scanning dependencies of target intersection-graph-test
Scanning dependencies of target ellipse-test
Scanning dependencies of target line-test
Scanning dependencies of target bezier-test
Scanning dependencies of target affine-test
[ 18%] Building CXX object src/tests/CMakeFiles/intersection-graph-test.dir/intersection-graph-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/convex-hull-test.dir/convex-hull-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/elliptical-arc-test.dir/elliptical-arc-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/circle-test.dir/circle-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/bezier-test.dir/bezier-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/line-test.dir/line-test.cpp.o
[ 19%] Building CXX object src/tests/CMakeFiles/ellipse-test.dir/ellipse-test.cpp.o
[ 20%] Building CXX object src/tests/CMakeFiles/affine-test.dir/affine-test.cpp.o
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp: In member function ‘virtual void EllipseTest_Arcs_Test::TestBody()’:
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:49:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc1(e.arc(Point(5,0), Point(0,0), Point(0,10)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:58:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc1r(e.arc(Point(0,10), Point(0,0), Point(5,0)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:64:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc2(e.arc(Point(5,0), Point(10,20), Point(0,10)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:70:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc2r(e.arc(Point(0,10), Point(10,20), Point(5,0)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:77:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc3(e.arc(Point(5,0), Point(0,10), Point(5,20)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:84:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc4(e.arc(Point(5,0), Point(2.5,5), Point(0,10)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:92:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     std::auto_ptr<EllipticalArc> arc4r(e.arc(Point(0,10), Point(2.5,5), Point(5,0)));
          ^~~~~~~~
In file included from /usr/include/c++/6/memory:81:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /home/alexander/libs/lib2geom/src/2geom/pathvector.h:38,
                 from /home/alexander/libs/lib2geom/src/2geom/crossing.h:43,
                 from /home/alexander/libs/lib2geom/src/2geom/line.h:41,
                 from /home/alexander/libs/lib2geom/src/2geom/ellipse.h:43,
                 from /home/alexander/libs/lib2geom/src/tests/ellipse-test.cpp:38:
/usr/include/c++/6/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
[ 20%] Linking CXX executable convex-hull-test
[ 20%] Linking CXX executable circle-test
[ 20%] Built target convex-hull-test
Scanning dependencies of target angle-test
[ 20%] Building CXX object src/tests/CMakeFiles/angle-test.dir/angle-test.cpp.o
[ 20%] Built target circle-test
Scanning dependencies of target choose-test
[ 20%] Building CXX object src/tests/CMakeFiles/choose-test.dir/choose-test.cpp.o
[ 20%] Linking CXX executable line-test
[ 20%] Built target line-test
Scanning dependencies of target nl-vector-test
[ 20%] Building CXX object src/tests/CMakeFiles/nl-vector-test.dir/nl-vector-test.cpp.o
[ 20%] Linking CXX executable intersection-graph-test
[ 20%] Linking CXX executable elliptical-arc-test
[ 20%] Linking CXX executable bezier-test
[ 20%] Built target intersection-graph-test
Scanning dependencies of target polynomial-test
[ 21%] Building CXX object src/tests/CMakeFiles/polynomial-test.dir/polynomial-test.cpp.o
[ 21%] Built target bezier-test
[ 21%] Built target elliptical-arc-test
Scanning dependencies of target coord-test
Scanning dependencies of target rect-test
[ 21%] Building CXX object src/tests/CMakeFiles/coord-test.dir/coord-test.cpp.o
[ 21%] Building CXX object src/tests/CMakeFiles/rect-test.dir/rect-test.cpp.o
[ 21%] Linking CXX executable ellipse-test
[ 21%] Linking CXX executable choose-test
[ 21%] Built target ellipse-test
Scanning dependencies of target implicitization-test
[ 21%] Building CXX object src/tests/CMakeFiles/implicitization-test.dir/implicitization-test.cpp.o
[ 21%] Linking CXX executable affine-test
[ 21%] Built target choose-test
Scanning dependencies of target path-test
[ 21%] Building CXX object src/tests/CMakeFiles/path-test.dir/path-test.cpp.o
[ 21%] Built target affine-test
Scanning dependencies of target sbasis-test
[ 22%] Building CXX object src/tests/CMakeFiles/sbasis-test.dir/sbasis-test.cpp.o
[ 22%] Linking CXX executable coord-test
[ 22%] Built target coord-test
Scanning dependencies of target point-test
[ 22%] Building CXX object src/tests/CMakeFiles/point-test.dir/point-test.cpp.o
In file included from /home/alexander/libs/lib2geom/src/tests/rect-test.cpp:34:0:
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp: In instantiation of ‘void Geom::GenericRectTest_Emptiness_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = int]’:
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp:357:1:   required from here
/home/alexander/libs/lib2geom/src/gtest/gtest.h:8071:18: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(Geom::GenericRectTest<int>::OptCRect&)’
       ::testing::AssertionResult(expression)) \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:19328:3: note: in expansion of macro ‘GTEST_TEST_BOOLEAN_’
   GTEST_TEST_BOOLEAN_(condition, #condition, false, true, \
   ^~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp:254:5: note: in expansion of macro ‘EXPECT_TRUE’
     EXPECT_TRUE(oa);
     ^~~~~~~~~~~
In file included from /home/alexander/libs/lib2geom/src/tests/rect-test.cpp:34:0:
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17675:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17675:12: note:   no known conversion for argument 1 from ‘Geom::GenericRectTest<int>::OptCRect {aka Geom::GenericOptRect<int>}’ to ‘bool’
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17673:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17673:3: note:   no known conversion for argument 1 from ‘Geom::GenericRectTest<int>::OptCRect {aka Geom::GenericOptRect<int>}’ to ‘const testing::AssertionResult&’
In file included from /home/alexander/libs/lib2geom/src/tests/rect-test.cpp:34:0:
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp: In instantiation of ‘void Geom::GenericRectTest_Emptiness_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = double]’:
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp:357:1:   required from here
/home/alexander/libs/lib2geom/src/gtest/gtest.h:8071:18: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(Geom::GenericRectTest<double>::OptCRect&)’
       ::testing::AssertionResult(expression)) \
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:19328:3: note: in expansion of macro ‘GTEST_TEST_BOOLEAN_’
   GTEST_TEST_BOOLEAN_(condition, #condition, false, true, \
   ^~~~~~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/tests/rect-test.cpp:254:5: note: in expansion of macro ‘EXPECT_TRUE’
     EXPECT_TRUE(oa);
     ^~~~~~~~~~~
In file included from /home/alexander/libs/lib2geom/src/tests/rect-test.cpp:34:0:
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17675:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17675:12: note:   no known conversion for argument 1 from ‘Geom::GenericRectTest<double>::OptCRect {aka Geom::OptRect}’ to ‘bool’
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17673:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/home/alexander/libs/lib2geom/src/gtest/gtest.h:17673:3: note:   no known conversion for argument 1 from ‘Geom::GenericRectTest<double>::OptCRect {aka Geom::OptRect}’ to ‘const testing::AssertionResult&’
src/tests/CMakeFiles/rect-test.dir/build.make:62: recipe for target 'src/tests/CMakeFiles/rect-test.dir/rect-test.cpp.o' failed
make[2]: *** [src/tests/CMakeFiles/rect-test.dir/rect-test.cpp.o] Error 1
CMakeFiles/Makefile2:881: recipe for target 'src/tests/CMakeFiles/rect-test.dir/all' failed
make[1]: *** [src/tests/CMakeFiles/rect-test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 23%] Linking CXX executable angle-test
[ 23%] Built target angle-test
[ 24%] Linking CXX executable nl-vector-test
[ 24%] Linking CXX executable polynomial-test
[ 24%] Built target polynomial-test
[ 24%] Built target nl-vector-test
[ 24%] Linking CXX executable point-test
[ 24%] Built target point-test
[ 24%] Linking CXX executable implicitization-test
[ 24%] Built target implicitization-test
[ 24%] Linking CXX executable sbasis-test
[ 24%] Built target sbasis-test
[ 24%] Linking CXX executable path-test
[ 24%] Built target path-test
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tweenk** [comment]
Looks like `boost::optional` changed its `operator bool` to `explicit` in a recent version. This should be fixed by updating the included copy of Google Test. Testing a branch right now.

**Comment by tweenk** [comment]
Pushed an update to master - converted Google Test into a submodule. Please test whether this is still an issue.

**Comment by abrock** [comment]
I tested it with a fresh clone and with my fork and it works in both case, so I close this. This also makes #8 obsolete.
